insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Sheena Thurbon', 'Keys to Tulsa', '1/8/2022', '2/19/2024', 1);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Gerardo Yeskov', 'Islands in the Stream', '7/31/2021', '10/7/2023', 2);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Valaria Withams', 'Front Line, The', '8/9/2021', '7/14/2023', 3);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Ernestine Basketter', 'Late Mathias Pascal, The (a.k.a. The Living Dead Man) (Feu Mathias Pascal)', '5/25/2021', '10/18/2023', 4);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Emili Mulqueeny', 'Nothing But Ghosts (Nichts als Gespenster)', '9/25/2021', '1/3/2024', 5);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Liza Durbyn', 'Good Marriage, A (Beau mariage, Le)', '8/15/2021', '9/8/2023', 6);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Lovell Edgin', 'Bedrooms & Hallways', '1/22/2022', '3/23/2023', 7);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Agatha Harly', 'Great Beauty, The (Grande Bellezza, La)', '11/14/2021', '3/6/2024', 8);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Arvin Cliss', 'Twixt', '8/27/2021', '2/1/2024', 9);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Gertrude Havard', 'Not Without My Daughter', '1/25/2022', '1/29/2024', 10);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Idette Pickthorne', 'Grand Hotel', '3/29/2021', '8/28/2023', 11);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Tatum Greenin', 'Police, Adjective (Politist, adj.)', '9/30/2021', '9/28/2023', 12);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Edi Truswell', 'Have Dreams, Will Travel', '4/19/2021', '4/3/2023', 13);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Nicko Cobbe', 'Obsession', '1/17/2022', '7/5/2023', 14);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Raina Letherbury', 'J. Gang Meets Dynamite Harry, The (Jönssonligan & DynamitHarry)', '7/15/2021', '1/19/2024', 15);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Merry Grzegorczyk', 'Chandu the Magician', '11/18/2021', '12/11/2023', 16);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Joan Kunzelmann', 'Killjoy 2: Deliverance from Evil', '2/7/2022', '12/16/2023', 17);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Katuscha Urquhart', 'Taxing Woman, A (Marusa no onna)', '5/20/2021', '3/25/2023', 18);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Raye Frostdick', 'Company', '11/21/2021', '4/12/2023', 19);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Sylvia Laxston', 'If I Stay', '10/2/2021', '12/3/2023', 20);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Mireille Epinay', 'Comin'' at Ya!', '4/3/2021', '10/23/2023', 21);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Haskel Alfonsini', 'Unsinkable Molly Brown, The', '12/3/2021', '6/9/2023', 22);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Jarrod Searchfield', 'Carabineers, The (Carabiniers, Les)', '4/30/2021', '4/24/2023', 23);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Keene Gilphillan', 'Vanya on 42nd Street', '6/3/2021', '9/17/2023', 24);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Eula Agates', 'Harry + Max', '12/6/2021', '8/19/2023', 25);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Gabbey Cowthard', 'Aashiqui 2', '11/30/2021', '3/15/2023', 26);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Conrade Calabry', 'Miranda', '6/16/2021', '10/19/2023', 27);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Gaspar Phinnis', 'Class of Nuke ''Em High', '10/7/2021', '2/10/2024', 28);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Britt Candlin', 'Flesh', '12/18/2021', '3/27/2023', 29);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Gae Colisbe', 'Sun Valley Serenade', '10/18/2021', '9/15/2023', 30);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Hurley Shaddick', 'Cotton Club, The', '3/7/2022', '4/24/2023', 31);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Angelika Watling', 'Night Court', '7/29/2021', '9/4/2023', 32);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Ange Secombe', 'Feast', '6/10/2021', '11/16/2023', 33);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Malcolm Petrelli', 'Joker Is Wild, The (All the Way)', '9/28/2021', '10/25/2023', 34);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Stearn Bernardon', 'Naked Killer (Chik loh go yeung)', '9/14/2021', '5/22/2023', 35);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Dominica Pendlebury', 'Mist, The', '11/10/2021', '2/16/2024', 36);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Forest Orneles', 'Diary of a Chambermaid, The', '11/5/2021', '7/30/2023', 37);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Allistir Landon', 'Giant Mechanical Man, The', '2/10/2022', '2/15/2024', 38);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Cecile McIndrew', 'Ella Lola, a la Trilby', '11/7/2021', '10/22/2023', 39);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Izaak Lyfe', 'Andrei Rublev (Andrey Rublyov)', '11/28/2021', '12/20/2023', 40);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Kinsley Cropper', 'Trader Games (Krach)', '8/18/2021', '6/23/2023', 41);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Mariellen Christophers', 'Lookin'' to Get Out', '2/24/2022', '1/18/2024', 42);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Edwina Baudry', 'Thief Lord, The', '4/26/2021', '5/3/2023', 43);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Herold Degue', 'Impostors, The', '8/23/2021', '9/5/2023', 44);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Robina Kernan', 'Thumbsucker', '10/13/2021', '7/17/2023', 45);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Donny Elmer', 'Fall From Grace', '8/8/2021', '6/28/2023', 46);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Isabella Pattie', 'Benjamin Blümchen - Seine schönsten Abenteuer', '3/1/2022', '9/10/2023', 47);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Townie O''Dougherty', 'If It''s Tuesday, This Must Be Belgium', '5/1/2021', '10/19/2023', 48);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Mada Vamplers', 'Hellbound: Hellraiser II', '9/14/2021', '9/13/2023', 49);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Langsdon Garstang', 'Stranger than Fiction', '12/25/2021', '8/31/2023', 50);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Jacques Henfre', 'Carmina and Amen (Carmina y amén)', '11/4/2021', '9/22/2023', 51);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Andris Twinberrow', 'Shifty', '6/14/2021', '3/16/2023', 52);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Gunner Paradin', 'Our Little Girl', '1/12/2022', '7/6/2023', 53);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Glynnis Sliman', 'Addicted to Plastic', '2/11/2022', '3/10/2023', 54);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Noble Isaq', 'Mysterians, The (Chikyu Boeigun)', '9/29/2021', '3/12/2023', 55);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Vidovic Easterbrook', 'Dresser, The', '9/5/2021', '7/6/2023', 56);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Westbrook Faughnan', 'Earth vs. the Spider', '2/8/2022', '6/23/2023', 57);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Robbi Wickes', 'Arsenal', '2/25/2022', '1/7/2024', 58);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Gery McGuiney', 'Mean Guns', '1/13/2022', '3/31/2023', 59);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Gabey Lockwood', 'Super Mario Bros.', '9/22/2021', '12/9/2023', 60);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Angelica Stanman', 'Four Nights of a Dreamer (Quatre nuits d''un rêveur)', '7/12/2021', '7/26/2023', 61);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Kacy Bridgwater', 'Cat in the Hat, The', '8/13/2021', '10/29/2023', 62);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Burgess Santhouse', 'Voodoo Dawn', '3/8/2022', '9/6/2023', 63);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Benjamin Fernao', 'Source Code', '10/15/2021', '5/14/2023', 64);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Even Dorbin', 'Exit Humanity', '6/3/2021', '12/8/2023', 65);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Hetty Billson', 'Shakedown', '7/17/2021', '1/29/2024', 66);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Julian Itzcovich', 'Hush... Hush, Sweet Charlotte', '5/1/2021', '5/12/2023', 67);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Gaye Avesque', 'Vanilla Sky', '6/2/2021', '1/12/2024', 68);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Ritchie Pigford', 'Male and Female', '8/8/2021', '4/12/2023', 69);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Gertrude McGeachy', 'Evening', '5/20/2021', '7/5/2023', 70);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Elise Langrish', 'Betrayal', '10/30/2021', '3/26/2023', 71);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Pierce Cattini', 'Bridge, The (Die Brücke)', '10/9/2021', '12/9/2023', 72);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Reilly MacMenamie', 'Trail Beyond, The', '12/28/2021', '6/2/2023', 73);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Willis McReynold', 'True Romance', '4/21/2021', '11/23/2023', 74);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Georgetta Vannozzii', 'Red 2', '7/24/2021', '2/5/2024', 75);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Rikki McKillop', 'Goal II: Living the Dream', '11/20/2021', '6/3/2023', 76);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Marla Dochon', 'Woodstock', '7/8/2021', '12/16/2023', 77);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Adah Robic', 'Echoes from the Dead (Skumtimmen)', '12/26/2021', '7/16/2023', 78);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Toddy Ordemann', 'Introduction to Physics, An', '4/21/2021', '5/26/2023', 79);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Brooke MacIlwrick', 'Ace of Aces (a.k.a. Super Ace, The) (As des as, L'')', '9/14/2021', '11/30/2023', 80);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Tonya Mansfield', 'Snarveien (Detour)', '6/21/2021', '12/22/2023', 81);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Jamison Hadenton', 'Troubled Water (DeUsynlige)', '7/8/2021', '10/11/2023', 82);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Dianne Barnwall', 'Scanner Darkly, A', '12/14/2021', '7/1/2023', 83);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Zarah Fancett', 'Footloose', '4/7/2021', '6/11/2023', 84);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Iona Buttel', 'All the King''s Men', '11/30/2021', '8/15/2023', 85);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Dionne Cruickshank', 'Nuts', '8/20/2021', '4/2/2023', 86);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Marna De Beauchamp', 'Drogówka', '2/26/2022', '4/15/2023', 87);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Puff Muckian', 'Adrenaline Drive (Adorenarin doraibu)', '11/27/2021', '7/6/2023', 88);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Carry Inde', 'Trauma', '7/31/2021', '9/3/2023', 89);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Cal Conlaund', 'Firehouse Dog', '6/13/2021', '3/29/2023', 90);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Isadore Bothie', 'Doctor Dolittle', '5/27/2021', '9/25/2023', 91);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Sophronia Erie', 'Sudden Death', '1/27/2022', '6/9/2023', 92);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Rex Walkling', 'Dallas 362', '7/12/2021', '1/13/2024', 93);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Frazier Gravestone', 'Aamir', '10/9/2021', '2/6/2024', 94);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Cary Newland', 'Superman/Shazam!: The Return of Black Adam (DC Showcase Original Shorts Collection)', '7/2/2021', '11/19/2023', 95);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Elsie Hazeman', 'Zeitgeist: The Movie', '1/16/2022', '5/26/2023', 96);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Newton Coggings', 'Errors of the Human Body ', '9/28/2021', '10/13/2023', 97);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Nicolais McGruar', 'Fatal Attraction', '5/5/2021', '11/23/2023', 98);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Caitlin Whardley', 'America, America', '5/12/2021', '1/5/2024', 99);
insert into BOOKS (author_name, book_name, create_at, update_at, category_id) values ('Reinaldos Potapczuk', 'Carry on Cabby', '6/15/2021', '9/19/2023', 100);
